### ISSUE TITLE
Date Range with SINGLE Data Series?

### ISSUE THREAD

**Issue by jpmorris** [mikeasilva/blsAPI#3]
There doesn't seem to be any way to return a custom date range with a SINGLE data series.  For example this fails:

    payload <- list(
       'seriesid'=c('LAUCN550790000000003'),
       'startyear'=2007,
       'endyear'=2009)
     response <- blsAPI(payload, 2)
    json <- fromJSON(response)

yet this works:

    payload <- list(
       'seriesid'=c('LAUCN550790000000003', 'LAUCN550790000000003'),
       'startyear'=2007,
       'endyear'=2009)
     response <- blsAPI(payload, 2)
    json <- fromJSON(response)

Is this a limitation of the API?

**Comment by mikeasilva** [comment]
@jpmorris 

I have tested your payload using a PHP version and can say this is not a limitation of the API.  The problem lies with the way rjson's toJSON function works ([see line 70 of blsAPI.r](https://github.com/mikeasilva/blsAPI/blob/397f15dfed841dbd6c076e0b0e81cb8b185a97e8/R/blsAPI.R)).

```{r}
library(rjson)
payload <- list(
   'seriesid'=c('LAUCN550790000000003'),
   'startyear'=2007,
   'endyear'=2009)
toJSON(payload)
```
yields 
```{r}
{\"seriesid\":\"LAUCN550790000000003\",\"startyear\":2007,\"endyear\":2009} 
```
but in order to work with the API the series id needs to be enclosed in brackets like this: 
```{r}
{\"seriesid\":[\"LAUCN550790000000003\"],\"startyear\":2007,\"endyear\":2009}
```

When you have two series id's they are correctly encapsulated (and why your workaround works).  Thanks for alerting me to this issue.

**Comment by mikeasilva** [comment]
@jpmorris I have updated this package to fix this bug.  You can get the latest from CRAN or GitHub.  Just a reminder that you will need to use your API key so your payload should look like this:
```{r}
payload <- list(
  'seriesid'=c('LAUCN550790000000003'),
  'startyear'=2007,
  'endyear'=2009,
  'registrationKey'='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
```
Thanks for bringing this issue to my attention!

**Comment by jpmorris** [comment]
thanks!
